### ISSUE TITLE
Пользовательский предикат вместо matchProps

### ISSUE THREAD

**Issue by elite174** [awinogradov/condicom#4]
Сейчас такая же проблема, как и в bem-react: нужно матчится на конкретные значения пропсов, а иногда требуется проверка, есть ли prop вообще. 

Было бы круто писать свои функции-предикаты
```
export const LinkThemeColorful = withCondition<ILinkProps>(
    props => props.pseudo === true, ...
```

**Comment by awinogradov** [comment]
Посмотри внимательно документацию https://github.com/awinogradov/condicom#not-for-css-only
Там есть примеры с функцией предикатом. Там используется внешний хелпер matchProps, поэтому могло показаться, что апи схожее, но в этом и был смысл.
